version: "2"
services:
  reference-ui:
    image: openlmis/dev-ui:9.0.2-SNAPSHOT
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - cce-ui
      - ui-components
      - ui-layout
      - offline-ui
    depends_on:
      - auth-ui
      - fulfillment-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - cce-ui
      - ui-components
      - ui-layout
      - offline-ui
    logging:
      driver: 'json-file'
      options:
          max-file: 5
          max-size: 1m
  auth-ui:
    image: openlmis/auth-ui:6.2.6-SNAPSHOT
    volumes:
      - '/openlmis-auth-ui'
  fulfillment-ui:
    image: openlmis/fulfillment-ui:6.0.9-SNAPSHOT
    volumes:
      - '/openlmis-fulfillment-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:5.6.5-SNAPSHOT
    volumes:
      - '/openlmis-referencedata-ui'
  report-ui:
    image: openlmis/report-ui:5.2.6-SNAPSHOT
    volumes:
      - '/openlmis-report-ui'
  requisition-ui:
    image: openlmis/requisition-ui:7.0.5-SNAPSHOT
    volumes:
      - '/openlmis-requisition-ui'
  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:2.0.9-SNAPSHOT
    volumes:
     - '/openlmis-stockmanagement-ui'
  cce-ui:
    image: openlmis/cce-ui:1.0.9-SNAPSHOT
    volumes:
     - '/openlmis-cce-ui'
  ui-components:
    image: openlmis/ui-components:7.2.5-SNAPSHOT
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.1.9-SNAPSHOT
    volumes:
      - '/openlmis-ui-layout'
  offline-ui:
    image: openlmis/offline-ui:1.0.0-SNAPSHOT
    volumes:
      - '/openlmis-offline-ui'
  image:
    build: .
    image: openlmis/reference-ui
