version: "2"
services:
  reference-ui:
    image: openlmis/dev-ui:latest
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
    depends_on:
      - auth-ui
      - referencedata-ui
      - requisition-ui
      - report-ui
      - stockmanagement-ui
      - ui-components
      - ui-layout
  auth-ui:
    image: openlmis/auth-ui
    volumes:
      - '/openlmis-auth-ui'
  fulfillment-ui:
    image: openlmis/fulfillment-ui
    volumes:
      - '/openlmis-fulfillment-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui
    volumes: 
      - '/openlmis-referencedata-ui'
  report-ui:
    image: openlmis/report-ui
    volumes:
      - '/openlmis-report-ui'
  requisition-ui:
    image: openlmis/requisition-ui
    volumes:
      - '/openlmis-requisition-ui'
  stockmanagement-ui:
    image: openlmis/stockmanagement-ui
    volumes:
      - '/openlmis-stockmanagement-ui'
  ui-components:
    image: openlmis/ui-components
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout
    volumes:
      - '/openlmis-ui-layout'
  image:
    build: .
    image: openlmis/reference-ui
